# Copyright (C) 2022 Christian Meffert <christian.meffert@googlemail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


# OwnTone configuration file for MkDocs with the theme "Material for MkDocs"
# 
# Documentation for the different conig options:
# - https://squidfunk.github.io/mkdocs-material/
# - https://www.mkdocs.org/


# Project information
site_name: OwnTone
site_url: https://owntone.github.io/owntone-server/
site_author: OwnTone maintainers
site_description: >-
  Linux/FreeBSD DAAP (iTunes) and MPD media server with support for AirPlay
  devices (multiroom), Apple Remote (and compatibles), Chromecast, Spotify
  and internet radio. 

# Repository
repo_name: owntone/owntone-server
repo_url: https://github.com/owntone/owntone-server
#edit_uri: ""

# Configuration
theme:
  name: 'material'
  language: en
  features:
    - navigation.tabs
#    - navigation.sections
#    - navigation.indexes
    - navigation.top
  palette:
    - scheme: default
      primary: white
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  logo: assets/logo.svg

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/owntone/owntone-server

extra_css:
  - assets/extra.css

extra_javascript:
  - assets/extra.js

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Documentation:
    - Getting Started: getting-started.md
    - Installation: installation.md
    - Configuration: configuration.md
    - Building: building.md
    - Library: library.md
    - Control:
      - Mobile Device: control-clients/mobile.md
      - Desktop: control-clients/desktop.md
      - Browser: control-clients/web.md
      - API and CLI: control-clients/cli-api.md
    - Audio Outputs:
      - AirPlay: audio-outputs/airplay.md
      - Chromecast: audio-outputs/chromecast.md
      - Local Audio: audio-outputs/local-audio.md
      - Mobile Device: audio-outputs/mobile.md
      - Web: audio-outputs/web.md
      - Roku: audio-outputs/roku.md
      - Streaming: audio-outputs/streaming.md
    - Media Clients: media-clients.md
    - Artwork: artwork.md
    - Playlists and Radio: playlists.md
    - Smart Playlists: smart-playlists.md
    - Services Integration:
      - Spotify: integrations/spotify.md
      - LastFM: integrations/lastfm.md
    - Advanced Setup:
      - ALSA: advanced/outputs-alsa.md
      - PulseAudio: advanced/outputs-pulse.md
      - Radio Streams: advanced/radio-streams.md
      - Remote Access: advanced/remote-access.md
      - Multiple Instances: advanced/multiple-instances.md
  - JSON API: json-api.md
